name: Build & Release
on:
        push:
                branches:
                        - main
permissions:
        contents: write
jobs:
        build-and-release:
                runs-on: ubuntu-latest
                steps:
                        -
                                name: Checkout
                                uses: actions/checkout@v5
                                with:
                                        fetch-depth: 0
                        -
                                name: Compile with Nix
                                uses: cachix/install-nix-action@v31
                                with:
                                        github_access_token: ${{ secrets.GITHUB_TOKEN }}
                        -
                                run: |
                                        nix run .#resume
                        -
                                name: Semantic Release
                                uses: cycjimmy/semantic-release-action@v5
                                env:
                                        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
